### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by majd-alhafi** [ayushayt/ImaginedSpeechRecognition#1]
Good afternoon Sir,
I am working on a similar project to decode the imagined speech.
Would you like to share the dataset?

**Comment by ayushayt** [comment]
Hello
The dataset used for this work is taken from Parimal Lab, Indian Institute of Technology Roorkee. You can find the dataset on http://parimal.iitr.ac.in/dataset

**Comment by majd-alhafi** [comment]
Thank you so much, Sir.
